### ISSUE TITLE
Feature Request: publish this extension to Open VSX Registry

### ISSUE THREAD

**Issue by garylavayou** [jackiotyu/vscode-quick-reference#2]
I just found this extension is very nice to use, especially in an offline environment.

Will it be possible to also port this extension to the Open VSX Registry, so that we can also install it for Web-based editors, such as code-server and open-vscode-server.

**Comment by jackiotyu** [comment]
Of course, I will complete it as soon as possible.

**Comment by jackiotyu** [comment]
It is now available on Open VSX.🤠
[open-vsx.org/extension/jackiotyu/quick-reference](https://open-vsx.org/extension/jackiotyu/quick-reference)

**Comment by garylavayou** [comment]
Thanks! It works.
